site_name: Campaign Manager
repo_url: https://github.com/systopia/de.systopia.campaign
theme: material

pages:
- 'About Campaign Manager': index.md
- 'Installation': installation.md
- 'The Campaign Dashboard': campaign-dashboard.md

markdown_extensions:
- attr_list
- admonition
- def_list
- codehilite
- toc:
    permalink: true
- pymdownx.superfences
- pymdownx.inlinehilite
- pymdownx.tilde
- pymdownx.betterem
- pymdownx.mark
